// Code generated by mockery v2.10.0. DO NOT EDIT.

package repository

import (
	helpers "github.com/adiatma85/golang-rest-template-api/pkg/helpers"
	mock "github.com/stretchr/testify/mock"

	models "github.com/adiatma85/golang-rest-template-api/internal/pkg/models"
)

// UserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type UserRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *UserRepositoryInterface) Create(user models.User) (models.User, error) {
	ret := _m.Called(user)

	var r0 models.User
	if rf, ok := ret.Get(0).(func(models.User) models.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: user
func (_m *UserRepositoryInterface) Delete(user *models.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWithIds provides a mock function with given fields: ids
func (_m *UserRepositoryInterface) DeleteWithIds(ids []uint64) error {
	ret := _m.Called(ids)

	var r0 error
	if rf, ok := ret.Get(0).(func([]uint64) error); ok {
		r0 = rf(ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *UserRepositoryInterface) GetAll() (*[]models.User, error) {
	ret := _m.Called()

	var r0 *[]models.User
	if rf, ok := ret.Get(0).(func() *[]models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: email
func (_m *UserRepositoryInterface) GetByEmail(email string) (*models.User, error) {
	ret := _m.Called(email)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: userId
func (_m *UserRepositoryInterface) GetById(userId string) (*models.User, error) {
	ret := _m.Called(userId)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: pagination
func (_m *UserRepositoryInterface) Query(pagination helpers.Pagination) (*helpers.Pagination, error) {
	ret := _m.Called(pagination)

	var r0 *helpers.Pagination
	if rf, ok := ret.Get(0).(func(helpers.Pagination) *helpers.Pagination); ok {
		r0 = rf(pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helpers.Pagination)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(helpers.Pagination) error); ok {
		r1 = rf(pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryWithCondition provides a mock function with given fields: q, pagination
func (_m *UserRepositoryInterface) QueryWithCondition(q *models.User, pagination helpers.Pagination) (*helpers.Pagination, error) {
	ret := _m.Called(q, pagination)

	var r0 *helpers.Pagination
	if rf, ok := ret.Get(0).(func(*models.User, helpers.Pagination) *helpers.Pagination); ok {
		r0 = rf(q, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helpers.Pagination)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.User, helpers.Pagination) error); ok {
		r1 = rf(q, pagination)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: user
func (_m *UserRepositoryInterface) Update(user *models.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
