// Code generated by mockery v2.10.0. DO NOT EDIT.

package helpers

import mock "github.com/stretchr/testify/mock"

// JWTCryptoHelper is an autogenerated mock type for the JWTCryptoHelper type
type JWTCryptoHelper struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: UserId
func (_m *JWTCryptoHelper) GenerateToken(UserId string) (string, error) {
	ret := _m.Called(UserId)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(UserId)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(UserId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *JWTCryptoHelper) ValidateToken(tokenString string) (bool, error) {
	ret := _m.Called(tokenString)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
