// Code generated by mockery v2.10.0. DO NOT EDIT.

package handler

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ProductHandlerInterface is an autogenerated mock type for the ProductHandlerInterface type
type ProductHandlerInterface struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: c
func (_m *ProductHandlerInterface) CreateProduct(c *gin.Context) {
	_m.Called(c)
}

// DeleteProductsWithIds provides a mock function with given fields: c
func (_m *ProductHandlerInterface) DeleteProductsWithIds(c *gin.Context) {
	_m.Called(c)
}

// DeleteSpecificProduct provides a mock function with given fields: c
func (_m *ProductHandlerInterface) DeleteSpecificProduct(c *gin.Context) {
	_m.Called(c)
}

// GetAllProduct provides a mock function with given fields: c
func (_m *ProductHandlerInterface) GetAllProduct(c *gin.Context) {
	_m.Called(c)
}

// GetSpecificProduct provides a mock function with given fields: c
func (_m *ProductHandlerInterface) GetSpecificProduct(c *gin.Context) {
	_m.Called(c)
}

// QueryProducts provides a mock function with given fields: c
func (_m *ProductHandlerInterface) QueryProducts(c *gin.Context) {
	_m.Called(c)
}

// UpdateSpecificProduct provides a mock function with given fields: c
func (_m *ProductHandlerInterface) UpdateSpecificProduct(c *gin.Context) {
	_m.Called(c)
}
